on:
  workflow_call:
    inputs:
      release_name:
        description: "Helm release name to deploy"
        type: string
      helm_options:
        description: "Options to pass to helm"
        type: string

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy kube
        env:
          HELM_RELEASE_NAME: ${{ inputs.release_name }}
          HELM_OPTIONS: ${{ inputs.helm_options }}
          ENVIRONEMNT: ${{ jobs.deploy.environment }}
        run: |
          echo "Deployment will proceed in $ENVIRONMENT"
          echo "Adding 'polyflix' repository to Helm ..."
          helm repo add polyflix https://polyflix.github.io/helm-charts
          echo "Deploying with following options: $HELM_OPTIONS"
          helm upgrade $HELM_RELEASE_NAME polyflix/service $HELM_OPTIONS \
            --dry-run
            --namespace "$ENVIRONMENT" \
            --dependency-update \
            --wait-for-jobs \
            --reuse-values \
            --install \
            --atomic
