on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: Run unit tests
        run: go test -v ./...
  package:
    # Package only if branch is main or tag
    if: github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/')
    uses: polyflix/.github/.github/workflows/package-image.yml@main