on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check_semver_labels:
    name: Check Semver labels
    runs-on: ubuntu-22.04

    steps:
      - name: Check for Semver labels
        uses: danielchabr/pr-labels-checker@v3.1
        with:
          hasSome: "semver: major,semver: minor,semver: patch"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
