on:
  workflow_call:
    inputs:
      package-migration:
        required: false
        type: boolean
        default: false

jobs:
  code_review:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Set npm registry access
        env:
          GITLAB_REGISTRY: ${{ secrets.GITLAB_REGISTRY_TOKEN }}
        run: |
          npm config set @polyflix:registry \
          https://gitlab.polytech.umontpellier.fr/api/v4/projects/1343/packages/npm/
          echo "//gitlab.polytech.umontpellier.fr/api/v4/projects/1343/packages/npm/:_authToken=$GITLAB_REGISTRY">.npmrc
      - run: npm ci
      - name: Audit
        continue-on-error: true
        run: npm audit
      - name: Lint
        run: npm run lint --if-present
      - name: Format
        run: npm run format:check --if-present

  build:
    runs-on: ubuntu-22.04
    needs: code_review
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Set npm registry access
        env:
          GITLAB_REGISTRY: ${{ secrets.GITLAB_REGISTRY_TOKEN }}
        run: |
          npm config set @polyflix:registry \
          https://gitlab.polytech.umontpellier.fr/api/v4/projects/1343/packages/npm/
          echo "//gitlab.polytech.umontpellier.fr/api/v4/projects/1343/packages/npm/:_authToken=$GITLAB_REGISTRY">.npmrc
      - name: Install npm
        run: npm ci
      - name: Build
        run: npm run build

      # Upload the dist directory if the branch is main or tag
      - name: Upload dist/ directory for packaging
        if: github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/
          retention-days: 1

  release:
    # Package only if branch is main
    if: github.ref == 'refs/heads/main'
    uses: polyflix/.github/.github/workflows/release-drafter.yml@main

  package:
    # Package only if branch is main or tag
    if: github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/')
    uses: polyflix/.github/.github/workflows/package-image.yml@main
    needs: build
    with:
      artifact-id: build
      artifact-download: true
      artifact-download-dir: dist

  package-migration:
    # Package only if branch is main or tag
    if: ${{ inputs.package-migration && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/')) }}
    uses: polyflix/.github/.github/workflows/package-image.yml@main
    needs: build
    with:
      artifact-id: build
      artifact-download: true
      artifact-download-dir: dist
      dockerfile-path: Dockerfile.migrations
      docker-metadata-flavor: suffix=migrations
