on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"
          cache: "maven"
      - name: Build
        env:
          MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Djansi.force=true"
          MAVEN_CLI_OPTS: "--errors --fail-at-end --show-version -Dstyle.color=always"
        run: mvn ${MAVEN_CLI_OPTS} clean package

      # Upload the target directory if the branch is main or tag
      - name: Upload target/ directory for packaging
        if: github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: target/
          retention-days: 1

  release:
    # Package only if branch is main
    if: github.ref == 'refs/heads/main'
    uses: polyflix/.github/.github/workflows/release-drafter.yml@main

  package:
    # Package only if branch is main or tag
    if: github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/')
    uses: polyflix/.github/.github/workflows/package-image.yml@main
    needs: build
    with:
      artifact-id: build
      artifact-download: true
      artifact-download-dir: target
